<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bagian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bagian_model');
        $this->load->library(array('form_validation','upload','image_lib','template','session'));
        $this->load->helper(array('form', 'url', 'html'));
        if(empty($this->session->userdata('id_user'))){
            redirect('user');
        }
    }

    public function index()
    {
        $bagian=$this->Bagian_model->get_all();
        $data = array(
        'title'     => 'Daftar Proyek ',
        'active'    => '',
        'active_header' => 'bagian',
        'bagian_data' => $bagian,
        );
        $this->template->display('bagian/bagian_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Bagian_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nm_bagian' => $row->nm_bagian,
	    );
            $this->template->display('bagian/bagian_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bagian'));
        }
    }

    public function create() 
    {
        $data = array(
            'title'     => 'Daftar Proyek ',
            'active'    => '',
            'active_header' => 'bagian',
            'button' => 'Create',
            'action' => site_url('bagian/create_action'),
	    'id' => set_value('id'),
	    'nm_bagian' => set_value('nm_bagian'),
	);
        $this->template->display('bagian/bagian_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nm_bagian' => $this->input->post('nm_bagian',TRUE),
	    );

            $this->Bagian_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bagian'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Bagian_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title'     => 'Daftar Proyek ',
                'active'    => '',
                'active_header' => 'bagian',
                'button' => 'Update',
                'action' => site_url('bagian/update_action'),
		'id' => set_value('id', $row->id_bagian),
		'nm_bagian' => set_value('nm_bagian', $row->nm_bagian),
	    );
            $this->template->display('bagian/bagian_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bagian'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nm_bagian' => $this->input->post('nm_bagian',TRUE),
	    );

            $this->Bagian_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bagian'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Bagian_model->get_by_id($id);

        if ($row) {
            $this->Bagian_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bagian'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bagian'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nm_bagian', 'nm bagian', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bagian.php */
/* Location: ./application/controllers/Bagian.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-22 14:07:31 */
/* http://harviacode.com */