<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bahan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'bahan/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'bahan/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'bahan/index.html';
            $config['first_url'] = base_url() . 'bahan/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Bahan_model->total_rows($q);
        $bahan = $this->Bahan_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'bahan_data' => $bahan,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('bahan/bahan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Bahan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_sumber' => $row->id_sumber,
		'nm_bahaya' => $row->nm_bahaya,
	    );
            $this->load->view('bahan/bahan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bahan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('bahan/create_action'),
	    'id' => set_value('id'),
	    'id_sumber' => set_value('id_sumber'),
	    'nm_bahaya' => set_value('nm_bahaya'),
	);
        $this->load->view('bahan/bahan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_sumber' => $this->input->post('id_sumber',TRUE),
		'nm_bahaya' => $this->input->post('nm_bahaya',TRUE),
	    );

            $this->Bahan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bahan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Bahan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('bahan/update_action'),
		'id' => set_value('id', $row->id),
		'id_sumber' => set_value('id_sumber', $row->id_sumber),
		'nm_bahaya' => set_value('nm_bahaya', $row->nm_bahaya),
	    );
            $this->load->view('bahan/bahan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bahan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_sumber' => $this->input->post('id_sumber',TRUE),
		'nm_bahaya' => $this->input->post('nm_bahaya',TRUE),
	    );

            $this->Bahan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bahan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Bahan_model->get_by_id($id);

        if ($row) {
            $this->Bahan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bahan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bahan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_sumber', 'id sumber', 'trim|required');
	$this->form_validation->set_rules('nm_bahaya', 'nm bahaya', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bahan.php */
/* Location: ./application/controllers/Bahan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-22 14:04:32 */
/* http://harviacode.com */