<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sumber extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(array('Sumber_model','Bagian_model'));
        $this->load->library(array('form_validation','upload','image_lib','template','session'));
        $this->load->helper(array('form', 'url', 'html'));
        if(empty($this->session->userdata('id_user'))){
            redirect('user');
        }
    }

    public function index()
    {
     $sumber=$this->Sumber_model->get_all(); 
        $data = array(
            'title'     => 'Daftar Sumber Bahaya ',
            'active'    => '',
            'active_header' => 'sumber',
            'sumber_data' => $sumber,
        );
        $this->template->display('sumber/sumber_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Sumber_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_bagian' => $row->id_bagian,
		'nm_sumber' => $row->nm_sumber,
	    );
            $this->template->display('sumber/sumber_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumber'));
        }
    }

    public function create() 
    {
        $data_bagian=$this->Bagian_model->get_all();
        $data = array(
            'title'     => 'Daftar Sumber Bahaya ',
            'active'    => '',
            'active_header' => 'sumber',
            'button' => 'Create',
            'action' => site_url('sumber/create_action'),
	    'id' => set_value('id'),
	    'id_bagian' => set_value('id_bagian'),
        'nm_sumber' => set_value('nm_sumber'),
        'data_bagian' => $data_bagian
	);
        $this->template->display('sumber/sumber_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_bagian' => $this->input->post('id_bagian',TRUE),
		'nm_sumber' => $this->input->post('nm_sumber',TRUE),
	    );

            $this->Sumber_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sumber'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Sumber_model->get_by_id($id);
        $data_bagian=$this->Bagian_model->get_all();
        if ($row) {
            $data = array(
                'title'     => 'Daftar Sumber Bahaya ',
                'active'    => '',
                'active_header' => 'sumber',
                'button' => 'Update',
                'action' => site_url('sumber/update_action'),
		'id' => set_value('id', $row->id_sumber),
		'id_bagian' => set_value('id_bagian', $row->id_bagian),
        'nm_sumber' => set_value('nm_sumber', $row->nm_sumber),
        'data_bagian' => $data_bagian
	    );
            $this->template->display('sumber/sumber_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumber'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_bagian' => $this->input->post('id_bagian',TRUE),
		'nm_sumber' => $this->input->post('nm_sumber',TRUE),
	    );

            $this->Sumber_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sumber'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Sumber_model->get_by_id($id);

        if ($row) {
            $this->Sumber_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sumber'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sumber'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_bagian', 'id bagian', 'trim|required');
	$this->form_validation->set_rules('nm_sumber', 'nm sumber', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sumber.php */
/* Location: ./application/controllers/Sumber.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-22 14:07:32 */
/* http://harviacode.com */