<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Identifikasi_model extends CI_Model
{

    public $table = 'identifikasi';
    public $id = 'id_identifikasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_proyek($id){
        $sql="Select
        proyek.identifikasi.severity,
        proyek.identifikasi.pengendalian,
        proyek.identifikasi.likelihood,
        proyek.bahaya.nm_bahaya,
        proyek.sumber.nm_sumber,
        proyek.bagian.nm_bagian,
        proyek.identifikasi.id_identifikasi,
        proyek.identifikasi.id_proyek,
        proyek.bagian.id_bagian
    From
        proyek.identifikasi Inner Join
        proyek.bahaya On proyek.bahaya.id_bahaya = proyek.identifikasi.id_bahaya Inner Join
        proyek.sumber On proyek.sumber.id_sumber = proyek.bahaya.id_sumber Inner Join
        proyek.bagian On proyek.bagian.id_bagian = proyek.sumber.id_bagian
    where
    proyek.identifikasi.id_proyek=$id
    ";
    return $this->db->query($sql);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_proyek', $q);
	$this->db->or_like('id_sumber', $q);
	$this->db->or_like('likelihood', $q);
	$this->db->or_like('severity', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_proyek', $q);
	$this->db->or_like('id_sumber', $q);
	$this->db->or_like('likelihood', $q);
	$this->db->or_like('severity', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Identifikasi_model.php */
/* Location: ./application/models/Identifikasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-22 14:07:31 */
/* http://harviacode.com */